[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-audit --no-fund"
  NETLIFY_CLEAR_BUILD_CACHE = "true"

# Clear cache on every build
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
